repos:
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
    -   id: codespell
        args:
        - -L ned
        - --builtins clear,rare,informal,usage,code,names,en-GB_to_en-US
